defaultPlacement: end
descriptionFormat: '{product.title} - {title}'
enableVersioning: false
handle: sorenmobler
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
isStructure: false
maxLevels: null
maxVariants: null
name: Sorenmobler
productFieldLayouts:
  b4d78e8a-1ebb-4ca9-af29-eeb784e8d96a:
    cardView:
      - defaultSku
      - defaultPrice
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-15T07:13:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: eb201297-7bbd-4ce0-a30e-db282c0184e9
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            dateAdded: '2025-03-15T07:13:54+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 0884f75d-0b17-46e3-928b-1b6f6fd3eeca
            userCondition: null
            warning: null
        name: Content
        uid: e5d9a18b-20bf-4cb9-a472-0f46dff9becd
        userCondition: null
productTitleFormat: ''
productTitleTranslationKeyFormat: null
productTitleTranslationMethod: site
propagationMethod: all
siteSettings:
  a42aa75e-70e1-44a8-867b-71f11ba1bc16: # testsite
    enabledByDefault: true
    hasUrls: true
    template: ''
    uriFormat: 'sorenmobler/{slug}'
skuFormat: ''
variantFieldLayouts:
  c73db97f-609a-4a1e-9ebe-3d7b136dfe70:
    cardView:
      - sku
      - priceView
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-15T07:13:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: c6da8f18-088b-466c-9eed-694bd96600bc
            userCondition: null
            warning: null
            width: 100
          -
            attribute: sku
            dateAdded: '2025-03-15T07:13:54+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: 1b200589-9cc8-4387-9163-b2bd63c258fc
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2025-03-15T07:13:54+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: 76f6d5ab-9c47-4236-8674-dafbebec39f4
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            dateAdded: '2025-03-15T07:13:54+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: f5381447-a313-4c5a-8a7c-03eced2c7a55
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            dateAdded: '2025-03-15T07:13:54+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: acfe88bc-cc5e-429b-a40e-d3f5e9b5bad7
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            dateAdded: '2025-03-15T07:13:54+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: b2ea02b4-8e68-4643-adef-d5255cdb5433
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            dateAdded: '2025-03-15T07:13:54+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: 50ae90c9-9ca6-43b1-b25e-0f13a9b519b1
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            dateAdded: '2025-03-15T07:13:54+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: 4e7ee2b4-2818-451e-9657-fa45f5ab6d16
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            dateAdded: '2025-03-15T07:13:54+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: cb49ec90-4590-428e-bc31-0432b8c92d68
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            dateAdded: '2025-03-15T07:13:54+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: 17a4cda0-7c31-4738-89ca-30a53f5a7680
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50859623-057c-48a6-95ca-0a83a751403d
        userCondition: null
variantTitleFormat: '{product.title}'
variantTitleTranslationKeyFormat: null
variantTitleTranslationMethod: site
