app: testsite
ssh_url: testsite@deploy.eu2.frbit.com
git_remote: testsite/master
before:
    code/up: {  }
after:
    code/down:
        - 'php craft migrate/all'
        - 'php craft project-config/apply'
