color: null
fieldLayouts:
  0ee78fc6-ff43-400b-9236-9e0c0a197ee8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-03T19:50:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d819cc33-d2f3-473c-8da7-4ac5cff523b1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-03T20:47:15+00:00'
            elementCondition: null
            fieldUid: 97d3dfc7-ca9f-40fb-9c60-eb3e8239136b # Test Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a72d4a1-7875-499c-8291-3d11f2655884
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-03T23:36:59+00:00'
            elementCondition: null
            fieldUid: 4c86be29-2c47-4966-b320-1cdae9b25580 # Project Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46a665e6-a72a-4609-b24d-608128e7273f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 737141a0-02aa-43ea-98b5-f73bb82f4723
        userCondition: null
handle: home
hasTitleField: true
icon: null
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
