defaultPlacement: end
fieldLayouts:
  294eedc1-05c4-496d-b9ea-68deea66bef1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-06T19:43:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: a10a27a3-b4ab-497c-b487-d38708957a66
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 239b68f8-803d-44ba-842e-5d11a9b7e834
        userCondition: null
handle: projects
name: Projects
siteSettings:
  a42aa75e-70e1-44a8-867b-71f11ba1bc16: # testsite
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 3d289a6d-69c0-4f34-b9c5-8d0ccbf65499
