columnSuffix: null
handle: projectSummary
instructions: null
name: 'Project Summary'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 0ca2aadd-5e32-458e-9b96-c3bbabef37f7 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
