dateModified: 1740952370
email:
  fromEmail: jennnnifer.harper@gmail.com
  fromName: testsite
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    8f81e28d-8195-41d2-a911-205d5b098a9c: testsite # testsite
    a42aa75e-70e1-44a8-867b-71f11ba1bc16: testsite # testsite
plugins:
  copy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: testsite
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
