dateModified: 1741161756
email:
  fromEmail: $EMAIL
  fromName: testsite
  replyToEmail: $EMAIL
  template: null
  transportSettings:
    command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDisk:
    hasUrls: true
    name: 'Hard Disk'
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
meta:
  __names__:
    0ca2aadd-5e32-458e-9b96-c3bbabef37f7: Simple # Simple
    4c86be29-2c47-4966-b320-1cdae9b25580: 'Project Summary' # Project Summary
    6d0dd73a-7698-42f4-8892-80a464f6adfb: 'Main Image' # Main Image
    7bf5cf40-ee14-4355-8aab-b5de30475736: Home # Home
    8f81e28d-8195-41d2-a911-205d5b098a9c: testsite # testsite
    97d3dfc7-ca9f-40fb-9c60-eb3e8239136b: 'Test Text' # Test Text
    7670ce0b-9802-430e-b33a-91d0defaa5a0: 'Project Images' # Project Images
    a19d5dc6-7462-4a42-b009-e7aaf9c1cc04: Home # Home
    a42aa75e-70e1-44a8-867b-71f11ba1bc16: testsite # testsite
    b1e9f265-767c-4dca-9511-55b54f4a5701: Second # Second
    c9509ac1-cdb4-40d0-a9d5-1a885853f625: Work # Work
    d5d48233-e9b4-49a6-9c43-d1dd76c6da17: Images # Images
    eb2b13c2-2a0a-4eba-9f97-9fc580c4bae1: Work # Work
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  copy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  webhooks:
    edition: standard
    enabled: true
    schemaVersion: 2.4.0
system:
  edition: solo
  live: true
  name: testsite
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
